### ISSUE TITLE
TXTunes doesn't announce tracks from Apple Music

### ISSUE THREAD

**Issue by JeffreyATW** [foldericon/TXTunes#2]
When playing a playlist from "For You", nothing is printed via the `/itunes` command or auto-announce. 

Downloading the playlist and its tracks solves the problem, but I'd like to not have to download every playlist beforehand.

**Comment by foldericon** [comment]
I'm aware of that limitation and i can't do anything about it as of now, since Apple's scripting bridge doesn't support Apple Music. If Apple decides to do so, ill add support for Apple Music.

**Comment by foldericon** [comment]
Good news: It will work with Apple Music on macOS Sierra.
